variables:
  DEBIAN_FRONTEND: noninteractive
  RUST_VERSION: "1.34"

build:
  stage: build
  image: rust:$RUST_VERSION
  before_script:
    - rustc --version && cargo --version
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo build --release
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - target/
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - target/release/sentry-process
  tags:
    - docker
